#!/bin/bash
# TODO: Check if already added

# Let's see if there's been a commit-msg hook
rootPath=$(readlink -f ./$(git rev-parse --show-cdup))
FILE=$rootPath/.sql/.flagcommit
if [ -f $FILE ];
then
    git add $rootPath/.sql/revisions
    git commit --amend -C HEAD --no-verify
    git add $rootPath/.sql/.flagcommit
fi