#!/bin/bash
# TODO: Check if already added

# Get the root path of the project
rootPath=$(readlink -f ./$(git rev-parse --show-cdup))

# Let's call the export revision script
**php_path** $rootPath/.sql/import_revisions.php